controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
store-index:
    path: /
    controller: App\Controller\StoreController::index
cart:
    path: /cart
    controller: App\Controller\CartController::index